### ISSUE TITLE
Rewrite streams in Vue.js

### ISSUE THREAD

**Issue by jaywink** [jaywink/socialhome#202]
See high level description at http://socialhome.readthedocs.io/en/latest/roadmap.html#vue-js-app-s

Streams *currently* implemented features below which need to be replicated on the Vue.js side. Tick off when Vue.js side merged to master.

All the items on this list block removing old legacy streams code.

🚫  = blocked by missing API work.
🏆 = does not block releasing the Vue streams as default. Basically stuff not going to implement in legacy streams at all. Create separately tickets maybe if not implemented via this issue.

Stream types:
* [x] Public
* [x] Followed
* [x] Tags
* [x] Profile pinned
* [x] Profile all

Fetching content:
* [x] Stream should use Streams API to fetch correct content for each stream

Content loading (all streams):
* [x] Fetches and renders initially X content items when loading the stream.
* [x] Fetches more content items when scrolling down. Triggers when 5th last item scrolls to view. New content is placed on bottom (order by created date).
  * Content load more last_id must be the lowest "through" content ID in the stream
* [x] Fetches new content when "new posts" label is clicked by user. Content is placed on top (reverse order by created date).
  * [x] Bug: If more than one new post is fetched, the "new posts" label does not disappear. When there is one only, it disappears.
* [x] When "new posts" is clicked, jumps to top of page.

Websockets:
* [x] Creates websocket connection on stream load.
* [x] Shows "new posts" label when server pushes new content id.
* [x] Fix placement of "new posts label, should be horizontally centered, just below navbar
* [x] Maintains list of ID's for new content waiting on server.
* [x] Closes websocket connection when browsing away from stream. (should be automatic, listing for completeness).

Grid items:
* [x] Renders pre-rendered content
* [x] Renders profile small image and name (except if one of the profile streams)
* [x] Profile image or name click opens profile box with handle
* [x] Profile box has "profile", "(remote) home", "follow" and "unfollow" buttons
* [x] Shows content timestamp. Appends "(edited)" if the content is edited.
* [x] Content timestamp is a link to the "single content view"
* [x] Envelop icon shows amount of replies
* [x] Clicking envelop icon fetches replies from the server and shows them
  * [x] 🏆 When fetching replies, show a spinner (see #338)
  * [x] bug: masonry redraw should be done after replies render 
* [x] 🏆 Replies for shares are shown grouped separately with a "reply" button for each share separately
* [x] End of replies section has a "reply" button
* [x] Clicking reply button goes to reply create page
* [x] Has "edit" icon (if logged in and own content)
* [x] Has "delete" icon (if logged in and own content)
* [x] Bug: edit/delete icons are misaligned in grid items, should be one space after timestamp
* [x] Bug: follow/unfollow in grid items does not work
* [x] NSFW shield is removed and reapplied on click
  * [x] Bug: Image does not load after removing NSFW shield
* [x] Ensure all oembed's work
  * Seems currently twitter oembed is problematic. Fix somehow or use backend rendering?
  * [x] Fix twitter OEmbed sometimes not triggering masonry redraw after full rendering
  * ~~Don't fetch Twitter script if the page doesn't have twitter oembed's - for example single content page~~
  * [ ] 🏆 Twitter stream widget (iframe) doesn't seem to function properly in desktop browsers (tried ff dev edition and chromium), but works on mobile firefox? Timing issue?
* [x] Replies should not have share or reply icons

Stamped area:
* [x] Public, followed and tags streams have a generic description
* [x] Profile stream stamped area has profile information and actions (see below)

Profile stamped area:
* [x] Has large profile picture
* [x] Has name and handle
  * [x] Fix name not rendering currently, seems like only guid does
* [x] Has pinned content button (if local and has pinned content)
* [x] Has all content button
* [x] Has profile actions dropdown (if logged in and own profile) with various links to non-Vue pages.
  * [x] Bug: dropdown renders too much off to the left and is not wide enough for all the text:
  * [x] Bug: Organize profile content link leads to email settings
  * [x] Bug: Organize profile content page does not render when Vue streams setting is active. Instead normal profile view is rendered. Probably a backend issue.

* [x] Has (remote) home, follow and unfollow buttons if not own profile but logged in.
* [x] Has "followed profiles" count (which is a link to contacts if logged in and own profile)
* [x] Has "follower profiles" count
* [x] Ensure author profile box does render even on profile streams if the content is not by profile owner, ie it's a share

Translations:
* [x] Strings must be translatable, using translations from Django
* [ ] 🏆 All strings must use translated version from Django

Styling:
* [x] 🏆 Cross-check old vs new styling, for example reaction icons and new post pill which seem to have a different font and size due to switching from div's to b-button

Build tools:
* [x] Webpack `build` command should be used for production style build, `dev` for development build.

Error control:
* [x] 🏆 Ajax errors should present user with a notification (#322)

Single content view
* [x] 🏆 Rewrite using Vue
  * Does not block release but should be done ASAP afterwards if not possible before release. Blocks removing any old streams code.

#### Cleanup work

After Vue streams released and default (export to own issue afterwards?):

* [x] Ensure Twitter oembed's are fetched without script tags, see: https://dev.twitter.com/web/javascript/loading
* [x] Remove core stream templates, refactor so that `vue.html` becomes `base.html`
* [x] Remove template rendering related model methods
* [x] Remove streams.js?
* [ ] Clean up project.css

#### Notes to node admins on deploy

Stage 1 - Vue streams default

* When updating, admins *must* use `npm run build` instead of `grunt build` or `npm run dev`. This must be done  before `collectstatics` (like `grunt` before).

Stage 2 - Legacy streams removed
* tbd

**Comment by christophehenry** [comment]
> Fix placement of "new posts label, should be horizontally centered, just below navbar

Ah... Some CSS that broke with [that change, I suppose](https://github.com/jaywink/socialhome/pull/266/files#diff-f6bf769c688863e153cb8f8d589a3803R4). I should be really more careful.

**Comment by christophehenry** [comment]
@jaywink Can you add internationalisation to this task? We need to get rid of [translations](https://github.com/jaywink/socialhome/blob/master/socialhome/streams/views.py#L71).

**Comment by christophehenry** [comment]
You can tick:

* Fix placement of "new posts label, should be horizontally centered, just below navbar
* Maintains list of ID's for new content waiting on server.
* Content timestamp is a link to the "single content view"
* End of replies section has a "reply" button
* Bug: edit/delete icons are misaligned in grid items, should be one space after timestamp

**Comment by christophehenry** [comment]
You can tick :

* Public, followed and tags streams have a generic description

**Comment by jaywink** [comment]
@christophehenry alright, #332 finalized the streams API's (well, except for minor tweaks) 🎉

**Comment by christophehenry** [comment]
#teamwork :heart:

**Comment by jaywink** [comment]
@christophehenry I'll start working on the replies today or latest weekend 👍

**Comment by jaywink** [comment]
I realized there is something else that needs to be done before we can remove the `streams.js` legacy code and all the templates - the single content view. Even though it's technically not a stream, it uses the same code, to avoid duplication and to allow pushing notification of new replies to the view (which was never done but could have been done using the websockets code).

Maybe we can make vue streams default still before doing this, but it should be done right after, since otherwise we can't remove pretty much any old javascript.

**Comment by christophehenry** [comment]
Was Twitter's OEmbed fixed? I don't see any problem here:

![screenshot-2017-11-19 flying pig https twitter com captainswaggfr sta](https://user-images.githubusercontent.com/22097904/32991951-115a471a-cd45-11e7-8f51-08e292ca94dc.png)

**Comment by jaywink** [comment]
@christophehenry doesn't work for me at least. Are you sure that is a vue stream render, not the "legacy" jquery one?

**Comment by christophehenry** [comment]
> @christophehenry doesn't work for me at least. Are you sure that is a vue stream render, not the "legacy" jquery one?

Oh... It was a single post view. Not converted to Vue yet. Sorry for the noise.

**Comment by christophehenry** [comment]
> Bug: Image does not load after removing NSFW shield

The image keeps its `.nsfw` class. It's a clash between the old and the new code. Unhopefully, nothing to do on the Vue side since the post is generated on backend. I don't want to write a workearound for this since the old code is being removed when we release the Vue front. So I'd say it's not really a bug.

**Comment by christophehenry** [comment]
@jaywink: You can tick

> - [x] Fetches new content when "new posts" label is clicked by user. Content is placed on top (reverse order by created date).
> - [x] When "new posts" is clicked, jumps to top of page.

**Comment by christophehenry** [comment]
Damn, that issue was opened on 23 of july. Almost 6 months since we started working on that. I didn't expect it to be so big 😄

**Comment by jaywink** [comment]
@christophehenry hey I'm working currently on the profile follower/following counts and also the missing action buttons there, just so we don't conflict 👍

**Comment by jaywink** [comment]
Let's finally close this epic and handle the few little issues separately <3
